org: jiebackend
app: jie-payments
service: jie-payments

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getStripeEphemeralKeys:
    handler: handler.getStripeEphemeralKeys
    events:
      - http:
          path: /
          method: get
