org: jiebackend
app: jie-payments
service: jie-payments

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getStripeEphemeralKeys:
    handler: handler.getStripeEphemeralKeys
    events:
      - http:
          path: /
          method: get
          request:
            template:
              application/json: '{ "customer_name" : "$input.params(''customer_name'')", "customer_email" : "$input.params(''customer_email'')" }'
